name: tcc_app_flutter
description: "Aplicación Flutter para la evaluación interactiva de estilos de aprendizaje (TCC)."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  http: ^1.2.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  dio: ^5.4.3
  cached_network_image: ^3.3.1
  image_picker: ^1.1.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10
  animations: ^2.0.11
  form_validator: ^2.1.1
  flutter_local_notifications: ^17.2.3
  url_launcher: ^6.3.0
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
