version: '3.8'

services:
  db:
    build: .
    container_name: mysql_tcc
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tcc_db
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_tcc
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: always
